apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-success-rate
  labels:
    app.kubernetes.io/instance: smart-canary
spec:
  args:
  - name: app-name
  - name: success-status-code
  - name: success-threshold
    value: "0.99"
  - name: failure-threshold
    value: "0.99"
  - name: pod-stage
    value: ".*"
  metrics:
  - name: http-success-rate
    interval: 15s
    successCondition: result[0] > {{` {{ args.success-threshold }} `}}
    failureCondition: result[0] <= {{` {{ args.failure-threshold }} `}}
    failureLimit: 3
    count: 10
    provider:
      prometheus:
        address: http://prom-kube-prometheus-stack-prometheus.default.svc.cluster.local:9090
        query: |
          {{`
          sum(irate(http_requests_total{job="{{ args.app-name }}", stage=~"{{ args.pod-stage }}", statusCode=~"{{ args.success-status-code }}"}[5m]))
          /
          sum(irate(http_requests_total{job="{{ args.app-name }}", stage=~"{{ args.pod-stage }}"}[5m]))
          `}}
