apiVersion: v1
kind: Service
metadata:
  name: smart-canary
  labels:
    app: server
    app.kubernetes.io/instance: smart-canary
spec:
  selector:
    app: smart-canary
  ports:
    - protocol: TCP
      name: metrics
      port: 8080
      targetPort: 8080
      nodePort: 32002
  type: NodePort